DELETE FROM Catalogo
GO
INSERT INTO Catalogo 
VALUES(0,'TIPOS DE USUARIOS');
GO
DECLARE @IdPadre int = SCOPE_IDENTITY();

INSERT INTO Catalogo 
VALUES(@IdPadre,'ADMINISTRADOR');

INSERT INTO Catalogo 
VALUES(@IdPadre,'TRABAJADOR CHANDOZOS');

INSERT INTO Catalogo 
VALUES(@IdPadre,'TRABAJADOR PANADERIA');
GO

INSERT INTO Catalogo 
VALUES(0,'TIPOS DE PRODUCTOS');
GO
DECLARE @IdPadre int = SCOPE_IDENTITY();

INSERT INTO Catalogo 
VALUES(@IdPadre,'PRINCIPAL');

INSERT INTO Catalogo 
VALUES(@IdPadre,'SECUNDARIOS');

GO
INSERT INTO Catalogo 
VALUES(0,'TIPOS DE FACTURACION');
GO
DECLARE @IdPadre int = SCOPE_IDENTITY();
INSERT INTO Catalogo
VALUES (@IdPadre, 'SUBTOTAL')

INSERT INTO Catalogo
VALUES (@IdPadre, 'TOTAL')

INSERT INTO Catalogo
VALUES (@IdPadre, 'DESCUENTO')

INSERT INTO Catalogo
VALUES (@IdPadre, 'DESECHABLE')

INSERT INTO Catalogo
VALUES (@IdPadre, 'DOMICILIO')

INSERT INTO Catalogo
VALUES (@IdPadre, 'PROPINA')

